### ISSUE TITLE
[ERROR] ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by MathisLec** [nwg-piotr/nwg-displays#45]
Hello there,
I just installed nwg-displays on my Arch by launching install.sh.
When I try to launch the tool, I receive an error:
```bash
❯ nwg-displays
Traceback (most recent call last):
  File "/home/<user>/.venv/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.3.10', 'gui_scripts', 'nwg-displays')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/.venv/bin/nwg-displays", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/matou/.venv/lib/python3.11/site-packages/nwg_displays-0.3.10-py3.11.egg/nwg_displays/main.py", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

```
I tried to install all of [these](https://stackoverflow.com/questions/71369726/no-module-named-gi) but no change.
Can I get a little help? :)

**Comment by nwg-piotr** [comment]
Never use pip on Arch. We have packages for all python modules.

**Comment by nwg-piotr** [comment]
Also nwg-displays itself you can install from AUR, together with all dependencies.

**Comment by MathisLec** [comment]
Thanks for your answer,
I installed nwg-displays from AUR and get this error.
I did'nt use pip to.

**Comment by nwg-piotr** [comment]
You messed something with your python environment. See the error you pasted.

**Comment by MathisLec** [comment]
I did'nt get why I never have to use pip in Arch. I tried AUR installation with and without my venv but no change. Sorry I'm not so comfortable with python project management.

**Comment by nwg-piotr** [comment]
I'm afraid I can't help. Try searching Arch wiki.

**Comment by Mieluoxxx** [comment]
my solution is [there](https://pygobject.gnome.org/getting_started.html)
