### ISSUE TITLE
GURU ebuild does not work

### ISSUE THREAD

**Issue by WhitleyStriber** [nwg-piotr/nwg-displays#49]
The ebuild installs just fine, but I receive this error. I already tried installing gtk-layer-shell but it does not work. Is there a dependency missing or is the ebuild not setup correctly? Here is the output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 24, in <module>
    gi.require_version('GtkLayerShell', '0.1')
  File "/usr/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkLayerShell not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/nwg-displays", line 5, in <module>
    from nwg_displays.main import main
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 26, in <module>
    raise RuntimeError('\n\n' +
RuntimeError: 

If you haven't installed GTK Layer Shell, you need to point Python to the
library by setting GI_TYPELIB_PATH and LD_LIBRARY_PATH to <build-dir>/src/.
For example you might need to run:

GI_TYPELIB_PATH=build/src LD_LIBRARY_PATH=build/src python3 /usr/lib/python-exec/python3.11/nwg-displays
➜  ~ 
```

**Comment by nwg-piotr** [comment]
I know nothing on Gentoo, so the only thing I can say is that the `gi.require_version('GtkLayerShell', '0.1')` command execution was unsuccessful. Looks like a missing dependency. You need to contact the packager.

**Comment by brendanhoran** [comment]
@WhitleyStriber  You need the following installed:
`dev-python/i3ipc`
`gui-libs/gtk-layer-shell` with the `introspection` use flag enabled.

The `ebuild` needs to be fixed to reflect this, but that is not @nwg-piotr  responsibility :)
