### ISSUE TITLE
Not working with Hyprland headless displays

### ISSUE THREAD

**Issue by PolpOnline** [nwg-piotr/nwg-displays#53]
# Steps to reproduce: 
1. Create a headless display with `hyprctl output create headless` (as found in [Hyprland Wiki](http://wiki.hyprland.org/Configuring/Using-hyprctl/#output))
2. Run nwg-displays via terminal
3. The following error gets returned: 

<details>
<summary>Console</summary>

```
Settings: {'view-scale': 0.15, 'snap-threshold': 10, 'indicator-timeout': 500, 'custom-mode': [], 'use-desc': False}
Running on Hyprland
Traceback (most recent call last):
  File "/usr/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.3.14', 'gui_scripts', 'nwg-displays')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 1243, in main
    create_display_buttons()
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 559, in create_display_buttons
    outputs = list_outputs()
              ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_displays/tools.py", line 138, in list_outputs
    "refresh": float(parts[2]) * 1000}
               ^^^^^^^^^^^^^^^
ValueError: could not convert string to float: '(current)'
```

</details>

**Comment by nwg-piotr** [comment]
Does it still happen on the current version?

**Comment by PolpOnline** [comment]
No, thanks
