### ISSUE TITLE
Get SyntaxError on run

### ISSUE THREAD

**Issue by Memoraike** [nwg-piotr/nwg-displays#58]
Hi, thanks for your hard work! Faced a problem in the version: `nwg-displays 0.3.17-1`.

```
Traceback (most recent call last):
  File "/usr/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.3.17', 'gui_scripts', 'nwg-displays')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/nwg-displays", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/nwg_displays/main.py", line 34, in <module>
    from nwg_displays.tools import *
  File "/usr/lib/python3.11/site-packages/nwg_displays/tools.py", line 32
    hypr_dir = f"{os.getenv("XDG_RUNTIME_DIR")}/hypr" if os.path.isdir(
                             ^^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '('
```

**Environment**:
**WM**: sway
**OS**: arch

**Comment by nwg-piotr** [comment]
I can't reproduce it on my machine. Could you show me your `printenv` output?

**Comment by Memoraike** [comment]
```
SHELL=/bin/zsh
WLR_RENDERER_ALLOW_SOFTWARE=1
LANGUAGE=en_GB.UTF-8
I3SOCK=/run/user/1000/sway-ipc.1000.49467.sock
SSH_AUTH_SOCK=/run/user/1000/gcr/ssh
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
XCURSOR_SIZE=24
PWD=/home/meow
LOGNAME=meow
XDG_SESSION_TYPE=wayland
SYSTEMD_EXEC_PID=49454
_=/usr/bin/printenv
DESKTOP_STARTUP_ID=5e005845ea8baf7fd5bf47efde03fac8
HOME=/home/meow
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=sway
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/sway.service/memory.pressure
SWAYSOCK=/run/user/1000/sway-ipc.1000.49467.sock
WAYLAND_DISPLAY=wayland-1
INVOCATION_ID=abe40840b34541d2894733cb22e81590
MANAGERPID=3408
USER=meow
NOTIFY_SOCKET=/run/user/1000/systemd/notify
DISPLAY=:0
SHLVL=2
XDG_RUNTIME_DIR=/run/user/1000
WLR_DRM_NO_MODIFIERS=1
JOURNAL_STREAM=8:463850
XDG_DATA_DIRS=/home/meow/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
PATH=/home/meow/.sdkman/candidates/java/current/bin:/home/meow/.volta/bin:/opt/flutter/bin:/home/meow/.bun/bin:/home/meow/.volta/bin:/home/meow/.console-ninja/.bin:/home/meow/.cargo/bin:/usr/local/bin:/usr/bin:/home/meow/.local/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/meow
LIBSEAT_BACKEND=logind
KITTY_WINDOW_ID=1
TERM=xterm-kitty
COLORTERM=truecolor
KITTY_PID=137171
KITTY_PUBLIC_KEY=1:&Pxwhs1!52=&rJ)+|Ccoe+1!{DcXo#BKfb&DAN=d
TERMINFO=/usr/lib/kitty/terminfo
KITTY_INSTALLATION_DIR=/usr/lib/kitty
OLDPWD=/home/meow
ZDOTDIR=/home/meow/.config/zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:
P9K_TTY=old
_P9K_TTY=/dev/pts/2
LESS_TERMCAP_mb=[01;32m
LESS_TERMCAP_md=[01;32m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_se=[0m
LESS_TERMCAP_so=[01;47;34m
LESS_TERMCAP_ue=[0m
LESS_TERMCAP_us=[01;36m
LS_OPTIONS=--color=auto
P9K_SSH=0
_P9K_SSH_TTY=/dev/pts/2
VOLTA_HOME=/home/meow/.volta
BUN_INSTALL=/home/meow/.bun
FLUTTER_INSTALL=/opt/flutter
CHROME_EXECUTABLE=google-chrome-stable
ANDROID_HOME=/home/meow/Android/Sdk
NDK_HOME=/home/meow/Android/Sdk/ndk/26.2.11394342
SDKMAN_DIR=/home/meow/.sdkman
SDKMAN_CANDIDATES_API=https://api.sdkman.io/2
SDKMAN_PLATFORM=linuxx64
SDKMAN_CANDIDATES_DIR=/home/meow/.sdkman/candidates
JAVA_HOME=/home/meow/.sdkman/candidates/java/current
```

**Comment by nwg-piotr** [comment]
Still no idea. It works well on all my 3 machines. :/ Furthermore: this line of code should be never executed on sway (if `$SWAYSOCK` value is set). One more question: why are you still on python3.11? Arch upgraded the python version a week ago.

**Comment by nwg-piotr** [comment]
OK, got it. The error only occurs on python<3.12. Fix on the way.

**Comment by Memoraike** [comment]
@nwg-piotr , thanks! Found out at the same time that I have a problem with pacman :D

**Comment by nwg-piotr** [comment]
Haha! The latest release should not crash on 3.11. Or at least I think so.
