### ISSUE TITLE
Cant Disable Any Monitor in Hyprland

### ISSUE THREAD

**Issue by bugra455** [nwg-piotr/nwg-displays#76]
Hello, i have a small issue for like 6 months or so. I cant disable any monitor in my Hyprland desktop.

One small note too, i cant see the toggle button near the 'monitor disabling menu'.

Distro: CachyOS (based on Arch)
WM: Hyprland, latest (v0.44.1)
All Intel hardware

inxi -Fx
```

System:
  Host: rael-cachy Kernel: 6.11.4-5-cachyos arch: x86_64 bits: 64
    compiler: clang v: 18.1.8
  Desktop: Hyprland v: 0.44.1 Distro: CachyOS base: Arch Linux
Machine:
  Type: Laptop System: Acer product: Aspire A315-58 v: V1.35
    serial: <superuser required>
  Mobo: TGL model: Camellia_TL v: V1.35 serial: <superuser required>
    UEFI: Insyde v: 1.35 date: 07/10/2023
Battery:
  ID-1: BAT1 charge: 39.3 Wh (100.0%) condition: 39.3/53.0 Wh (74.1%)
    volts: 16.6 min: 15.4 model: PANASONIC AP19B5L status: full
CPU:
  Info: quad core model: 11th Gen Intel Core i5-1135G7 bits: 64 type: MT MCP
    arch: Tiger Lake rev: 1 cache: L1: 320 KiB L2: 5 MiB L3: 8 MiB
  Speed (MHz): avg: 400 min/max: 400/4200 cores: 1: 400 2: 400 3: 400 4: 400
    5: 400 6: 400 7: 400 8: 400 bogomips: 38707
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel TigerLake-LP GT2 [Iris Xe Graphics]
    vendor: Acer Incorporated ALI driver: i915 v: kernel arch: Gen-12.1
    bus-ID: 00:02.0
  Device-2: Quanta HD User Facing driver: uvcvideo type: USB bus-ID: 1-8:4
  Display: wayland server: X.Org v: 24.1.3 with: Xwayland v: 24.1.3
    compositor: Hyprland v: 0.44.1 driver: gpu: i915 resolution:
    1: 1920x1080~75Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: iris,swrast platforms:
    active: gbm,wayland,x11,surfaceless,device inactive: N/A
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: mesa v: 24.2.5-cachyos1.2
    glx-v: 1.4 direct-render: yes renderer: llvmpipe (LLVM 18.1.8 256 bits)
Audio:
  Device-1: Intel Tiger Lake-LP Smart Sound Audio
    vendor: Acer Incorporated ALI driver: sof-audio-pci-intel-tgl
    bus-ID: 00:1f.3
  API: ALSA v: k6.11.4-5-cachyos status: kernel-api
  Server-1: sndiod v: N/A status: off
  Server-2: JACK v: 1.9.22 status: off
  Server-3: PipeWire v: 1.2.5 status: active
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi v: kernel bus-ID: 00:14.3
  IF: wlan0 state: up mac: bc:f1:71:d4:95:e0
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: Acer Incorporated ALI driver: r8169 v: kernel port: 3000
    bus-ID: 02:00.0
  IF: enp2s0 state: down mac: 08:8f:c3:8b:4b:b0
Bluetooth:
  Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) driver: btusb
    v: 0.8 type: USB bus-ID: 1-10:5
  Report: btmgmt ID: hci0 rfk-id: 2 state: down bt-service: disabled
    rfk-block: hardware: no software: no address: N/A
Drives:
  Local Storage: total: 704.24 GiB used: 115.85 GiB (16.5%)
  ID-1: /dev/nvme0n1 vendor: Kingston model: OM8PDP3256B-AA1
    size: 238.47 GiB temp: 33.9 C
  ID-2: /dev/sda vendor: SanDisk model: SDSSDH3 500G size: 465.76 GiB
Partition:
  ID-1: / size: 463.26 GiB used: 115.67 GiB (25.0%) fs: btrfs dev: /dev/sda3
  ID-2: /boot size: 1.9 GiB used: 177.9 MiB (9.1%) fs: ext4 dev: /dev/sda2
  ID-3: /boot/efi size: 511 MiB used: 1.3 MiB (0.3%) fs: vfat dev: /dev/sda1
  ID-4: /home size: 463.26 GiB used: 115.67 GiB (25.0%) fs: btrfs
    dev: /dev/sda3
  ID-5: /var/log size: 463.26 GiB used: 115.67 GiB (25.0%) fs: btrfs
    dev: /dev/sda3
  ID-6: /var/tmp size: 463.26 GiB used: 115.67 GiB (25.0%) fs: btrfs
    dev: /dev/sda3
Swap:
  ID-1: swap-1 type: zram size: 19.32 GiB used: 0 KiB (0.0%) dev: /dev/zram0
Sensors:
  System Temperatures: cpu: 30.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 20 GiB available: 19.32 GiB used: 2.41 GiB (12.5%)
  Processes: 264 Uptime: 11m Init: systemd
  Packages: 1512 Compilers: clang: 18.1.8 gcc: 14.2.1 Shell: Zsh v: 5.9
    inxi: 3.3.36
```

Log of nwg-displays while running it from terminal
```

(nwg-displays:3367): Gtk-WARNING **: 08:37:55.131: Unknown key dgtk-theme-name in /home/rael/.config/gtk-3.0/settings.ini
Settings: {'view-scale': 0.15, 'snap-threshold': 10, 'indicator-timeout': 500, 'custom-mode': [], 'use-desc': False, 'confirm-timeout': 10}
Running on Hyprland
eDP-1 {'active': True, 'mirror': '', 'scale_filter': None, 'modes': [{'width': 1920, 'height': 1080, 'refresh': 60000.0}], 'focused': False, 'adaptive_sync_status': 'disabled', 'description': 'BOE 0x0818', 'x': 0, 'y': 0, 'refresh': 60.0, 'logical-width': 1920.0, 'logical-height': 1080.0, 'physical-width': 1920, 'physical-height': 1080, 'transform': 'normal', 'scale': 1.0, 'dpms': True, 'ten_bit': False, 'model': '0x0818', 'monitor': <__gi__.GdkWaylandMonitor object at 0x71a0df045a40 (GdkWaylandMonitor at 0x6045698b7a80)>}
HDMI-A-1 {'active': True, 'modes': [{'width': 1920, 'height': 1080, 'refresh': 60000.0}, {'width': 1920, 'height': 1080, 'refresh': 74970.0}, {'width': 1920, 'height': 1080, 'refresh': 60000.0}, {'width': 1920, 'height': 1080, 'refresh': 59940.0}, {'width': 1920, 'height': 1080, 'refresh': 50000.0}, {'width': 1680, 'height': 1050, 'refresh': 59880.0}, {'width': 1280, 'height': 1024, 'refresh': 75030.0}, {'width': 1280, 'height': 1024, 'refresh': 60020.0}, {'width': 1440, 'height': 900, 'refresh': 59900.0}, {'width': 1280, 'height': 960, 'refresh': 60000.0}, {'width': 1280, 'height': 720, 'refresh': 60000.0}, {'width': 1280, 'height': 720, 'refresh': 60000.0}, {'width': 1280, 'height': 720, 'refresh': 59940.0}, {'width': 1280, 'height': 720, 'refresh': 50000.0}, {'width': 1024, 'height': 768, 'refresh': 75030.0}, {'width': 1024, 'height': 768, 'refresh': 70070.0}, {'width': 1024, 'height': 768, 'refresh': 60000.0}, {'width': 832, 'height': 624, 'refresh': 74550.0}, {'width': 800, 'height': 600, 'refresh': 75000.0}, {'width': 800, 'height': 600, 'refresh': 72190.0}, {'width': 800, 'height': 600, 'refresh': 60320.0}, {'width': 800, 'height': 600, 'refresh': 56250.0}, {'width': 720, 'height': 576, 'refresh': 50000.0}, {'width': 720, 'height': 576, 'refresh': 50000.0}, {'width': 720, 'height': 576, 'refresh': 50000.0}, {'width': 720, 'height': 480, 'refresh': 60000.0}, {'width': 720, 'height': 480, 'refresh': 60000.0}, {'width': 720, 'height': 480, 'refresh': 59940.0}, {'width': 720, 'height': 480, 'refresh': 59940.0}, {'width': 720, 'height': 480, 'refresh': 59940.0}, {'width': 640, 'height': 480, 'refresh': 75000.0}, {'width': 640, 'height': 480, 'refresh': 72810.0}, {'width': 640, 'height': 480, 'refresh': 66670.0}, {'width': 640, 'height': 480, 'refresh': 60000.0}, {'width': 640, 'height': 480, 'refresh': 59940.0}, {'width': 640, 'height': 480, 'refresh': 59940.0}, {'width': 720, 'height': 400, 'refresh': 70080.0}], 'mirror': '', 'scale_filter': None, 'focused': True, 'adaptive_sync_status': 'disabled', 'description': 'Philips Consumer Electronics Company PHL 242V8 UHB2049003115', 'x': 1920, 'y': 0, 'refresh': 74.97, 'logical-width': 1920.0, 'logical-height': 1080.0, 'physical-width': 1920, 'physical-height': 1080, 'transform': 'normal', 'scale': 1.0, 'dpms': True, 'ten_bit': False, 'model': 'PHL 242V8', 'monitor': <__gi__.GdkWaylandMonitor object at 0x71a0df045a80 (GdkWaylandMonitor at 0x6045698b8750)>}
[Saving]
# Generated by nwg-displays on 2024-10-22 at 08:39:18. Do not edit manually.

monitor=eDP-1,1920x1080@60.0,0x0,1.0
monitor=HDMI-A-1,1920x1080@74.97,1920x0,1.0
monitor=HDMI-A-1,disable
[Saving]
# Generated by nwg-displays on 2024-10-22 at 08:39:21. Do not edit manually.

monitor=eDP-1,1920x1080@60.0,0x0,1.0
monitor=HDMI-A-1,1920x1080@74.97,1920x0,1.0
[Saving]
# Generated by nwg-displays on 2024-10-22 at 08:39:27. Do not edit manually.

monitor=eDP-1,1920x1080@60.0,0x0,1.0
monitor=eDP-1,disable
monitor=HDMI-A-1,1920x1080@74.97,1920x0,1.0
[Saving]
# Generated by nwg-displays on 2024-10-22 at 08:39:31. Do not edit manually.

monitor=eDP-1,1920x1080@60.0,0x0,1.0
monitor=HDMI-A-1,1920x1080@74.97,1920x0,1.0
^CTraceback (most recent call last):
  File "/usr/bin/nwg-displays", line 33, in <module>
    sys.exit(load_entry_point('nwg-displays==0.3.22', 'gui_scripts', 'nwg-displays')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_displays-0.3.22-py3.12.egg/nwg_displays/main.py", line 1344, in main
    Gtk.main()
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gtk.py", line 1681, in main
    with register_sigint_fallback(Gtk.main_quit):
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/lib/python3.12/site-packages/gi/_ossighelper.py", line 239, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

```

_What Does it Do_: Nothing
_What Is Expected_: Closing the selected monitor after clicking _apply_ button or the existence of _toggle_ button

**Comment by bugra455** [comment]
I had forgotten to say I tried both AUR version and Git version. The log I posted is made by latest Git.

**Comment by nwg-piotr** [comment]
Well, I see no single error message coming from the nwg-displays code itself. Mystery. Have you fixed the typo in gtk settings.ini yet? Maybe this is the reason?

```
Unknown key dgtk-theme-name in /home/rael/.config/gtk-3.0/settings.ini
```

**Comment by bugra455** [comment]
Thanks for your answer. Unfortunately yesterday i switched to another distro so i can't confirm it (but it didn't caused any problems, its been like 2 months) but it happens in a fresh install too.

**Comment by JackMasterJack** [comment]
I had a similar problem and my work around is disabling the screen (screensaver style) with a keybind. After that you can easily disable that monitor in nwg-display

My keybind:

-- "current" disables the screen your cursor is on but you can set it to a specific monitor
-- https://wiki.hypr.land/Configuring/Basics/Monitors/  
hl.bind(mainMod .. " + O", hl.dsp.dpms({ action = "toggle", monitor = "current" }))
